### ISSUE TITLE
subject listed as environment

### ISSUE THREAD

**Issue by carlmcqueen** [jooyoungseo/mboxr#1]
Maybe not a problem at all, but a lot of the subjects when brought in from the archive file are listed as 'environment' -- Is it possible to get this text out to a character as your example shows?

Thanks

**Comment by jooyoungseo** [comment]
I am sorry for late response @carlmcqueen,

It has been resolved: 767a7d0.
Please install the dev version of this package as this has not yet been submitted to CRAN:

```{r}
if(!require(remotes)) {
install.packages("remotes")
}

remotes::install_github("jooyoungseo/mboxr")
```

Please keep me posted about whether this addresses your probem as well.
Thanks.
